version: "3"
services:
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    volumes:
      - /mnt/sata2-1/app/chinesesubfinder/config:/config # 冒号左边请修改为你想在主机上保存配置、日志等文件的路径
      - /mnt/sata2-1/media:/media # 请修改为你的媒体目录，冒号右边可以改成你方便记忆的目录，多个媒体目录需要分别映射进来
      - /mnt/sata2-1/app/chinesesubfinder/browser:/root/.cache/rod/browser # 容器重启后无需再次下载 chrome，除非 go-rod 更新
    environment:
      - PUID=0 # uid
      - PGID=0 # gid
      - PERMS=false # 是否重设/media权限
      - TZ=Asia/Shanghai # 时区
      - UMASK=022 # 权限掩码
    restart: unless-stopped
    network_mode: bridge
    hostname: chinesesubfinder
    ports:
      - 19035:19035 # 从0.20.0版本开始，通过webui来设置
      - 19037:19037 # webui 的视频列表读取图片用，务必设置不要暴露到外网
    logging:
      driver: "json-file"
      options:
        max-size: "100m" # 限制docker控制台日志大小，可自行调整
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    environment:
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /mnt/sata2-1/app/jackett/data:/config
      - /mnt/sata2-1/downloads/watch:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  jellyfin:
    image: jellyfin/jellyfin

    network_mode: "bridge"
    volumes:
      - /mnt/sata2-1/app/jellyfin/config:/config
      - /mnt/sata2-1/app/jellyfin:/cache
      - /mnt/sata2-1/app/jellyfin/media:/media
    restart: "unless-stopped"
    ports:
      - 31020:8096
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin.home.stardamnsucks.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
  transmission:
    image: lscr.io/linuxserver/transmission:latest

    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME= #optional
      - USER= #optional
      - PASS= #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - /mnt/sata2-1/app/transmission/data:/config
      - /mnt/sata2-1/downloads/file:/downloads
      - /mnt/sata2-1/downloads/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
